### ISSUE TITLE
Really bad contrast of status bar when in debug

### ISSUE THREAD

**Issue by levrik** [smlombardi/theme-slime#2]
I opened a ticket over by VS Code itself (Microsoft/vscode#27324) since the foreground color while debugging is not possible to change.

![image](https://cloud.githubusercontent.com/assets/9491603/26490650/80f1464c-420c-11e7-90ee-0c018c2a4f4d.png)

**Comment by levrik** [comment]
This is now possible to change with `statusBar.debuggingForeground`.

**Comment by smlombardi** [comment]
Fixed in d289dcfbe7bed00fb8f1910df9a6f0e915910aa7

Thanks for the PR, I didn't notice it till today!  I added your code to master.

**Comment by levrik** [comment]
@smlombardi wohoo. thanks for merging 🎉
